import React, { useState } from "react";
import {
  Card,
  CardContent,
  Grid,
  Typography,
  IconButton,
  Box,
  Link,
  Button,
  Link as MUILink,
} from "@mui/material";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import AdminPanelSettingsIcon from "@mui/icons-material/AdminPanelSettings";
import RolePage from "./Roles";
interface RoleCardProps {
  title: string;
  description: string;
  icon?: React.ReactNode;
}
const newBulkRolesData = [
  {
    id: 1,
    name: "Bulk Actions",
    description: "",
    allowed: false,
    disabled: false,
  },
  {
    id: 2,
    name: "Bulk Edit",
    description:
      "Edit the status or custom fields on leads or contacts in bulk.",
    allowed: false,
    disabled: true,
  },
  {
    id: 3,
    name: "Bulk Delete",
    description: "Delete leads or contacts in bulk.",
    allowed: false,
    disabled: true,
  },
  {
    id: 4,
    name: "Bulk Import",
    description: "Import of data via CSV/Excel.",
    allowed: false,
    disabled: true,
  },
  {
    id: 5,
    name: "Export",
    description: "Bulk export lead or opportunity data to a CSV or JSON file.",
    allowed: false,
    disabled: true,
  },
  {
    id: 6,
    name: "Bulk Email",
    description: "Send bulk emails to contacts.",
    allowed: false,
    disabled: true,
  },
  {
    id: 7,
    name: "Bulk Update",
    description: "Update multiple records at once.",
    allowed: false,
    disabled: true,
  },
];

const rolesData = [
  {
    id: 1,
    name: "Organization Permissions",
    description: "",
    allowed: false,
    disabled: false,
  },
  {
    id: 2,
    name: "Manage Users",
    description: "Manage user accounts and permissions.",
    allowed: false,
    disabled: true,
  },
  {
    id: 3,
    name: "Edit Content",
    description: "Edit and manage content on the platform.",
    allowed: false,
    disabled: true,
  },
  {
    id: 4,
    name: "View Reports",
    description: "View various reports generated by the system.",
    allowed: false,
    disabled: true,
  },
  {
    id: 5,
    name: "Manage Projects",
    description: "Manage and oversee ongoing projects.",
    allowed: false,
    disabled: true,
  },
];

const RoleCard: React.FC<RoleCardProps> = ({ title, description, icon }) => {
  return (
    <Card variant="outlined" sx={{ width: 250, height: "70px" }}>
      <CardContent>
        <Box
          display="flex"
          justifyContent="space-between"
          alignItems="center"
          mb={1}
          sx={{ mt: -1 }}>
          <Typography variant="body1" fontWeight="bold">
            {title}
          </Typography>
          {icon && <IconButton>{icon}</IconButton>}
        </Box>
        <Typography variant="body2" color="textSecondary" sx={{ mt: -2 }}>
          {description}
        </Typography>
      </CardContent>
    </Card>
  );
};

const UserRoles: React.FC = () => {
  const [isAddingRole, setIsAddingRole] = useState(false); // Track if adding role
  const [newRole, setNewRole] = useState(""); // For new role input

  const handleAddRoleClick = () => {
    setIsAddingRole(true); // Show the add role form
  };

  const handleSaveRole = () => {
    // Save the new role logic here
    console.log("Role saved:", newRole);

    // Reset the form and show roles list
    setIsAddingRole(false);
    setNewRole("");
  };

  return (
    <Box p={4}>
      {/* Conditionally show the add role form or the roles list */}
      {!isAddingRole ? (
        <Box>
          <Box sx={{ mb: 2 }}>
            <Typography sx={{ fontWeight: 400 }}>
              Roles allow to set users who can perform different actions. A role
              define actions within the app.
            </Typography>
            <MUILink
              href="https://your-link-here.com"
              sx={{ mt: 2, display: "block", textDecoration: "none" }}>
              Learn more about Roles and Permissions.
            </MUILink>
          </Box>
          <Grid container spacing={2}>
            <Grid item>
              <RoleCard
                title="Admin"
                description="Assigned to you"
                icon={<AdminPanelSettingsIcon sx={{ color: "orange" }} />}
              />
            </Grid>
            <Grid item>
              <RoleCard
                title="Super User"
                description="Not assigned to any users"
                icon={<ContentCopyIcon />}
              />
            </Grid>
            <Grid item>
              <RoleCard
                title="User"
                description="Not assigned to any users"
                icon={<ContentCopyIcon />}
              />
            </Grid>
            <Grid item>
              <RoleCard
                title="Restricted User"
                description="Not assigned to any users"
                icon={<ContentCopyIcon />}
              />
            </Grid>
            <Grid item>
              <Button
                sx={{
                  height: "70px",
                  width: 250,
                  border: "2px dotted gray",
                  backgroundColor: "#f9f9f9",
                  color: "black",
                }}
                onClick={handleAddRoleClick}>
                + Create a new role
              </Button>
            </Grid>
          </Grid>
        </Box>
      ) : (
        <Box>
          <Typography
            mb={2}
            sx={{
              border: "1px solid #e5f3ff",
              backgroundColor: "#e5f3ff",
              borderRadius: 2,
              padding: 2,
            }}>
            The users roles must always exit. Instead of editing you can copy
            it.
            <Link sx={{ ml: 1, textDecoration: "none" }}>Find out more.</Link>
          </Typography>

          <RolePage initialRoles={rolesData} />
          <RolePage initialRoles={newBulkRolesData} />
          <Button
            variant="contained"
            color="primary"
            onClick={handleSaveRole}
            sx={{ mr: 2 }}>
            Save Role
          </Button>
          <Button variant="outlined" onClick={() => setIsAddingRole(false)}>
            Cancel
          </Button>
        </Box>
      )}
    </Box>
  );
};

export default UserRoles;
